### ISSUE TITLE
SyntaxError 3d time with MHDDoS

### ISSUE THREAD

**Issue by alexnest-ua** [MHProDev/PyRoxy#14]
![image](https://user-images.githubusercontent.com/74729549/159267536-f0372658-c4c3-4210-bc00-ff649964283e.png)

root@ubuntu-switzeland:~/mhddos_proxy/MHDDoS# python3 start.py get https://sberbank.ru 5 1000 socks5.txt 100 100
Traceback (most recent call last):
  File "start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], chr] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length)
                                                                                      ^
SyntaxError: invalid syntax

This error not because of PyProxy directly, but because of not rebuilted MHDDoS

**Comment by MHProDev** [comment]
reinstall pyroxy

**Comment by alexnest-ua** [comment]
You need to mention how to do this...

Linux:
```shell
sudo apt install python3 -y
sudo apt upgrade python3 -y
sudo apt install python3-pip -y
sudo apt upgrade python3-pip -y
sudo -H pip3 install --upgrade pip
sudo rm -r MHDDoS
git clone https://github.com/MHProDev/MHDDoS.git
cd MHDDoS
sudo pip3 install -r requirements.txt
```

or if user uses mhddos_proxy:
```shell
cd ~
sudo rm -r mhddos_proxy
git clone https://github.com/porthole-ascend-cinnamon/mhddos_proxy.git
cd mhddos_proxy
git clone https://github.com/MHProDev/MHDDoS.git
sudo pip3 install -r MHDDoS/requirements.txt
```

On Windows install Git and Python3 and remove sudo from commands

**Comment by 235234dd** [comment]
how do i install pyroxy ...
